<?php
/******************************************************************************
 * (c) 2007-Present Kaity G. B. <uberChick -at- uberChicGeekChick.Com>        *
 * 	http://uberChicGeekChick.Com/                                         *
 * Released under the terms of:                                               *
 * 	the Reciprocal Public License ("RPL") Version 1.5.                    *
 *                                                                            *
 *                                                                            * 
 * For more about me & other uberChicks involved in:                          *
 * 	technology, science, & critical thinking:                             *
 * 	Please join or visit us @ http://uberChicks.Net/                      *
 *                                                                            * 
 * I also live with a progressive neuro-muscular movement disorder:           *
 * 	A type of Generalized Dystonia; A disease called:                     *
 * 		DYT1+ Early-Onset Generalized Dystonia.                       *
 * 	For more information please visit:                                    *
 * 		http://Dystonia-DREAMS.Org/                                   *
 * 			-or-                                                  *
 * 		http://Dystonia-Foundation.org                                *
 ******************************************************************************/

/*******************************************************************************
 * Unless explicitly acquired and licensed from Licensor under another         *
 * license, the contents of this file are subject to the Reciprocal Public     *
 * License ("RPL") Version 1.5, or subsequent versions as allowed by the RPL,  *
 * and You may not copy or use this file in either source code or executable   *
 * form, except in compliance with the terms and conditions of the RPL.        *
 *                                                                             *
 * All software distributed under the RPL is provided strictly on an "AS       *
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND     *
 * LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT            *
 * LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR     *
 * PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the RPL for specific     *
 * language governing rights and limitations under the RPL.                    *
 *                                                                             *
 * The User-Visible Attribution Notice below, when provided, must appear in    *
 * each user-visible display as defined in Section 6.4 (d) of the RPL:         *
 *                                                                             *
 * Initial art work including: design, logic, programming, and graphics are    *
 * Copyright (C) 2009 Kaity G. B. and released under the RPL where applicable. *
 * All materials not covered under the terms of the RPL are all still          *
 * Copyright (C) 2009 Kaity G. B. and released under  Creative Commons':       *
 *     Non-Comercial, Attribution, Share-A-Like version 3.0 US license.        *
 *                                                                             *
 * Any & all data stored by this Software created, generated, uploaded by,     *
 * and/or gathered by software connected, linked, or otherwise associatable    *
 * back to the User.  All such data stored, used, or in any way generated by   *
 * software is connected to any of software's users remains or becomes the     *
 * property of User to whom the data is connected, associated, and belongs to. *
 * All such User data will heretofor be referred to as "Data".                 *
 *                                                                             *
 * Users may agree to license their data under any license they choose or      *
 * to retain all and full copyright control over Data. As such Users must be   *
 * able allow or exempt any and all of their Data choice of license for all    *
 * Data and any use, outside of internal use by Software. User may be allowed  *
 * to select a default license for Data but must be also be allowed to except  *
 * any portion of Data and license or restrict any piece of User's said Data.  *
 * All of the Software's Data pertaining to each User must be fully            *
 * accessible, modifiable, exportable, and deletable by and to User.           *
 *                                                                             *
 * A full copy of this project's appended RPL 1.5 may be read in               *
 *     the projects file: "RPL 1.5.txt"                                        *
 *                                                                             *
 * The original RPL, version 1.5, may be viewed online at:                     *
 *		http://opensource.org/licenses/rpl1.5.txt                      *
 ******************************************************************************/


ini_set("display_errors", TRUE);
ini_set("error_reporting", E_ALL | E_STRICT);
ini_set("date.timezone", "America/Denver");

require_once("./__init.inc.php");

?>
