#!/bin/tcsh -f
set my_editor = "`printf "\""${0}"\"" | sed 's/.*\/\([^\.]\+\).*/\1/g'`"
switch ( "${my_editor}" )
case "connectED":
case "gedit":
	breaksw
case "vi":
case "vim":
case "vim-enhanced":
default:
	set my_editor = `printf "%s -p" "vim-enhanced"`
	breaksw
endsw

${my_editor} "./xml/xhtml/blocs/about_me/online_profiles.php" "./xml/xhtml/blocs/about_me/projects.php" "./xml/xhtml/blocs/support/openSuSE.php" "./xml/xhtml/blocs/support/raydium3d.php" "./xml/xhtml/body.php" "./xml/xhtml/stylesheets/speakingOUT.css"
