<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
	<head>
		<title>Podcasts for &amp; by Skeptics</title>
	</head>
	<body>
		<outline type="link" title="<![CDATA[Public Reality Radio]]>" url="http://www.publicrealityradio.org/browse.php" text="<![CDATA[Public Reality Radio]]>" description="<![CDATA[WPRR Public Reality Radio is a non-profit, listener supported radio station dedicated to providing quality educational programming to the public. In addition to locally produced shows and the best of progressive radio, WPRR showcases podcasts from around the world. Our mission is to bring to you intelligent and challenging programming from many diverse points of view on subjects ranging from philosophy and science to politics and religion. Reality Radio can be heard on AM 1680 in Grand Rapids, MI.]]>"/>
		<!--<outline type="link" title="<![CDATA[]]>" url="" text="<![CDATA[]]>" description="<![CDATA[]]>"/>-->
		<outline title="<![CDATA[Geologic Podcast]]>" xmlUrl="http://www.geologicpodcast.com/rss" type="rss" text="<![CDATA[Geologic Podcast]]>" htmlUrl="http://www.geologicpodcast.com/" description="<![CDATA[George Hrab and the Geologic Universe]]>"/>
<outline title="<![CDATA[Critical Mass]]>" xmlUrl="http://www.sydneyatheists.org/taxonomy/term/14/0/feed" type="rss" text="<![CDATA[The Critacal Mass Podcast: a healthy dose of skepticism.]]>" htmlUrl="http://www.sydneyatheists.org/" description="<![CDATA[The Critacal Mass Podcast, a healthy dose of skepticism.&nbsp; The official podcast of the Sydney Atheists]]>"/>
		<!--<outline title="<![CDATA[Critical Mass]]>" xmlUrl="http://feeds.feedburner.com/sydneyatheistspodcast?format=xml" type="rss" text="<![CDATA[Critacal Mass: Podcast]]>" htmlUrl="http://criticalmasspodcast.blogspot.com/" description="<![CDATA[The Critacal Mass Podcast, a healthy dose of skepticism.&nbsp; The official podcast of the Sydney Atheists]]>"/>-->
		<outline title="<![CDATA[SKepticZone Podcast]]>" xmlUrl="http://skepticzone.libsyn.com/rss" type="rss" text="<![CDATA[SkepticZone Podcast]]>" htmlUrl="http://skepticzone.libsyn.com/" description="<![CDATA[The Podcast from Australia for Science and Reason.]]>"/>
		<outline title="<![CDATA[Young Australian Skeptics]]>" xmlUrl="http://www.youngausskeptics.com/category/podcast/feed/" type="rss" text="<![CDATA[Young Australian Skeptics &#0187; Podcast]]>" htmlUrl="http://www.youngausskeptics.com/" description="<![CDATA[A Sanctuary for young free thinkers]]>"/>
		<outline title="<![CDATA[Skeptics Guide to the Universe]]>" text="<![CDATA[Skeptics Guide to the Universe]]>" xmlUrl="http://theskepticsguide.org/rss.xml" type="rss" htmlUrl="http://theskepticsguide.org/" description="<![CDATA[Skeptics Guide to the Universe: Your escape to reality.]]>"/>
		<outline title="<![CDATA[Skeptics Guide 5x5]]>" text="<![CDATA[]]>" xmlUrl="http://theskepticsguide.org/5x5/rss_5x5.xml" type="rss" htmlUrl="http://theskepticsguide.org/5x5/" description="<![CDATA[Skeptics Guide 5x5: A weekly dose of reality.]]>"/>
		<outline title="<![CDATA[Skepticality - Science and Revolutionary Ideas]]>" text="<![CDATA[Skepticality - Science and Revolutionary Ideas]]>" xmlUrl="" type="rss" htmlUrl="" description="<![CDATA[Skepticality - Science and Revolutionary Ideas.  The Official Podcast of Skeptic Magazine]]>"/>
		<outline title="<![CDATA[Dogma Free America]]>" text="<![CDATA[Dogma Free America]]>" xmlUrl="http://dogmafreeamerica.com/rss" type="rss" htmlUrl="http://dogmafreeamerica.com/" description="<![CDATA[]]>"/>
		<outline title="<![CDATA[Reason Driven Life]]>" text="<![CDATA[]]>" xmlUrl="http://feeds.feedburner.com/TheReasonDrivenPodcast?format=xml" type="rss" htmlUrl="" description="<![CDATA[Reason Driven Life: Dont believe everything you think]]>"/>
		<outline title="<![CDATA[reasonable doubts]]>" text="<![CDATA[your skeptical guide to religion]]>" xmlUrl="http://feeds.feedburner.com/reasonabledoubts/Msxh?format=xml" type="rss" htmlUrl="http://doubtcast.org/" description="<![CDATA[]]>"/>
		<outline title="<![CDATA[Digital Bits Skeptic]]>" xmlUrl="http://www.dbskeptic.com/podcast" type="rss" text="<![CDATA[Digital Bits Skeptic]]>" htmlUrl="http://www.dbskeptic.com/" description="<![CDATA[Skepticism and critical thinking in a world of new age, religion and credulous pop culture.]]>"/>
		<outline title="<![CDATA[Point of Inquiry]]>" xmlUrl="http://pointofinquiry.libsyn.com/rss" type="rss" text="<![CDATA[Point of Inquiry]]>" htmlUrl="http://www.pointofinquiry.org/" description="<![CDATA[Point of Inquiry is the premiere podcast of the Center for Inquiry, drawing on CFI&#039;s relationship with the leading minds of the day including Nobel Prize-winning scientists, public intellectuals, social critics and thinkers, and renowned entertainers.]]>"/>
		<outline title="<![CDATA[course of reason podcast]]>" xmlUrl="http://www.centerforinquiry.net/oncampus/podcast/courseofreason.xml" type="rss" text="<![CDATA[course of reason podcast]]>" htmlUrl="http://www.centerforinquiry.net/oncampus/news/course_of_reason_podcast/" description="<![CDATA[Justin Trottier, Tyler Handley, and Debbie Goddard discuss campus-related news and events in the world of freethought activism, engage in educational segments, conduct interviews and panels with freethought leaders from around the world, and provide student leaders with information and resources for successfully organizing, participating in, and running a campus freethought group.]]>"/>
		<outline title="<![CDATA[The Infidel Guy]]>" xmlUrl="http://infidelguy.libsyn.org/rss" type="rss" text="<![CDATA[The Infidel Guy]]>" htmlUrl="http://infidelguy.libsyn.org/" description="<![CDATA[For almost a decade the infidelguy show has brought you entertaining and educational programs not heard anywhere else.]]>"/>
		<outline title="<![CDATA[With Good Reason]]>" xmlUrl="http://feeds.feedburner.com/WithGoodReasonRadio?format=xml" type="rss" text="<![CDATA[With Good Reason Radio]]>" htmlUrl="http://www.withgoodreasonradio.org/podcast-page/" description="<![CDATA[Each week on With Good Reason, our ever-curious host Sarah McConnell takes you along as she examines a wide range of topics with leading scholars. Featured guests have included Julian Bond discussing race in America, Bruce Grayson sharing his study of near death experiences, Mike Seeger exploring American folk music, Aniko Bodroghkozy tuning in on sixties television, Bryan Caplan on the &quot;myth of the rational voter,&quot; Nikki Giovanni reading from her poetry, and Lawrence Weinstein describing-through a process called &quot;guesstimation&quot;-how big your feet would have to be in order to walk on water. You may discover the traditions of the samurai warrior, hear about the ways we pre-judge others based on their accents, or laugh at the surprising history of Hawaiian shirts.]]>"/>
		<!--<outline title="<![CDATA[]]>" xmlUrl="" type="rss" text="<![CDATA[]]>" htmlUrl="" description="<![CDATA[]]>"/>-->
	</body>
</opml>
